// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj48LPnml60Eq7YLsAp7eS_YPDLAxMGJk',
    appId: '1:301584586281:web:6e0651488fa00acf90ee38',
    messagingSenderId: '301584586281',
    projectId: 'mynotes-c8a3e',
    authDomain: 'mynotes-c8a3e.firebaseapp.com',
    storageBucket: 'mynotes-c8a3e.appspot.com',
    measurementId: 'G-M0MTPNL2K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkgdUoBJZTxaaZbAfu-0O7KFl2kEn8egE',
    appId: '1:301584586281:android:9d4b0a8f6a92d13190ee38',
    messagingSenderId: '301584586281',
    projectId: 'mynotes-c8a3e',
    storageBucket: 'mynotes-c8a3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUtcqWBt6iMpK21p51r8yzup6lWNMDmho',
    appId: '1:301584586281:ios:5ef19ef5b0d7301b90ee38',
    messagingSenderId: '301584586281',
    projectId: 'mynotes-c8a3e',
    storageBucket: 'mynotes-c8a3e.appspot.com',
    iosClientId: '301584586281-n631vdb9cpmcb3q9pftkfrfht9k4gcb3.apps.googleusercontent.com',
    iosBundleId: 'ma.hachami.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUtcqWBt6iMpK21p51r8yzup6lWNMDmho',
    appId: '1:301584586281:ios:5ef19ef5b0d7301b90ee38',
    messagingSenderId: '301584586281',
    projectId: 'mynotes-c8a3e',
    storageBucket: 'mynotes-c8a3e.appspot.com',
    iosClientId: '301584586281-n631vdb9cpmcb3q9pftkfrfht9k4gcb3.apps.googleusercontent.com',
    iosBundleId: 'ma.hachami.mynotes',
  );
}
